name: Build and Deploy Portfolio to EKS

on:
  workflow_dispatch:

env:
  ECR_REPOSITORY: 211125578268.dkr.ecr.us-east-1.amazonaws.com/portfolio
  AWS_REGION: us-east-1  # Change to your AWS region
  EKS_CLUSTER_NAME: ted # Change to your cluster name
  K8S_NAMESPACE: portfolio
  APP_NAME: portfolio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
        docker push ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
        echo "image=${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update kubeconfig for EKS cluster
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Update K8s manifest with new image
      run: |
        # Replace the image placeholder in your existing K8s manifest
        sed -i "s|image:.*|image: ${{ steps.build-image.outputs.image }}|g" kubernetes/*.yaml
        
    - name: Deploy to Kubernetes
      run: |
        # Apply the existing K8s manifests in the kubernetes directory
        kubectl apply -f kubernetes/